In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
df=pd.read_excel(r"C:\Users\Gnanajothi.M\OneDrive\Desktop\call_centre_performance_Analysis_system\datasets\call_center (1).xlsx",header=None)

calls table

In [113]:
calls=pd.read_excel(r"C:\Users\Gnanajothi.M\OneDrive\Desktop\call_centre_performance_Analysis_system\datasets\call_center (1).xlsx",header=2,usecols="B:H")

In [33]:
calls.head()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,128,4.9
1,Call_7272,C0004,119,R05,2023-01-01,135,2.9
2,Call_7273,C0005,68,R02,2023-01-01,66,4.7
3,Call_7274,C0014,119,R02,2023-01-01,22,2.9
4,Call_7275,C0011,128,R01,2023-01-02,31,2.8

customers table

In [105]:
customers=pd.read_excel(r"C:\Users\Gnanajothi.M\OneDrive\Desktop\call_centre_performance_Analysis_system\datasets\call_center (1).xlsx",header=2,usecols="L:O",nrows=15)

In [31]:
customers.head()

  Customer ID.1 Gedner   Age        City
0         C0001   Male  41.0    Columbus
1         C0002   Male  31.0   Cleveland
2         C0003   Male  26.0  Cincinnati
3         C0004   Male  36.0  Cincinnati
4         C0005   Male  37.0    Columbus

In [34]:
calls.tail()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
995,Call_8266,C0002,81,R05,2023-12-30,28,3.9
996,Call_8267,C0007,127,R04,2023-12-30,215,3.8
997,Call_8268,C0013,146,R05,2023-12-31,115,2.3
998,Call_8269,C0010,123,R05,2023-12-31,64,3.7
999,Call_8270,C0009,114,R01,2023-12-31,40,3.9

In [35]:
customers.tail()

    Customer ID.1 Gedner  Age City
995           NaN    NaN  NaN  NaN
996           NaN    NaN  NaN  NaN
997           NaN    NaN  NaN  NaN
998           NaN    NaN  NaN  NaN
999           NaN    NaN  NaN  NaN

In [81]:
calls.sample(5)

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
411,Call_7682,C0005,27,R03,2023-04-24,74,4.0
526,Call_7797,C0012,48,R01,2023-06-05,120,4.1
942,Call_8213,C0005,80,R05,2023-11-28,148,4.1
757,Call_8028,C0002,152,R04,2023-09-27,88,4.7
514,Call_7785,C0015,94,R02,2023-05-30,180,4.7

In [83]:
customers

   Customer ID.1  Gedner  Age        City
0          C0001    Male   41    Columbus
1          C0002    Male   31   Cleveland
2          C0003    Male   26  Cincinnati
3          C0004    Male   36  Cincinnati
4          C0005    Male   37    Columbus
5          C0006    Male   23    Columbus
6          C0007  Female   22   Cleveland
7          C0008  Female   42   Cleveland
8          C0009  Female   25    Columbus
9          C0010  Female   30   Cleveland
10         C0011  Female   30  Cincinnati
11         C0012  Female   28  Cincinnati
12         C0013  Female   37   Cleveland
13         C0014  Female   38    Columbus
14         C0015  Female   43   Cleveland

In [84]:
type(calls)

pandas.DataFrame

In [85]:
calls.shape

(1000, 7)

In [86]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='str')

to know the datatype in entire table

In [88]:
calls.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   str
 1   Customer ID          1000 non-null   str
 2   Duration             1000 non-null   int64
 3   Representative       1000 non-null   str
 4   Date of Call         1000 non-null   datetime64[us]
 5   Purchase Amount      1000 non-null   int64
 6   Satisfaction Rating  1000 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 54.8 KB

In [90]:
calls.describe()

,Duration,Date of Call,Purchase Amount,Satisfaction Rating
count,1000.000000,1000,1000.000000,1000.000000
mean,89.850000,2023-06-15 00:34:33.600000,96.623000,3.885400
min,2.000000,2023-01-01 00:00:00,20.000000,0.000000
25%,62.000000,2023-03-20 00:00:00,50.000000,3.400000
50%,89.000000,2023-05-25 12:00:00,88.000000,4.000000
75%,119.000000,2023-09-24 00:00:00,130.000000,4.500000
max,176.000000,2023-12-31 00:00:00,225.000000,5.000000
std,37.626736,NaN,52.465794,0.835551

question
total calls
peak duration
best representative
average duration of call
highest purchaseamount
busy day
age wise analysis
city wise analysis

In [91]:
calls.isnull()

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False

In [114]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               0
Representative         0
Date of Call           0
Purchase Amount        0
Satisfaction Rating    3
dtype: int64

In [115]:
customers.isnull().sum()

Customer ID.1    0
Gedner           0
Age              0
City             0
dtype: int64

it shows which row contain null value:contains it diplay true or false

In [122]:
calls.isnull().any(axis=1)

0       True
1       True
2       True
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [117]:
calls.isnull().all()

Call number            False
Customer ID            False
Duration               False
Representative         False
Date of Call           False
Purchase Amount        False
Satisfaction Rating    False
dtype: bool

In [118]:
calls[calls.isnull().any(axis=1)]

,Call number,Customer ID,Duration,Representative,Date of Call,Purchase Amount,Satisfaction Rating
0,Call_7271,C0003,116,R05,2023-01-01,128,NaN
1,Call_7272,C0004,119,R05,2023-01-01,135,NaN
2,Call_7273,C0005,68,R02,2023-01-01,66,NaN

In [127]:
calls["Satisfaction Rating"]=calls["Satisfaction Rating"].fillna(calls["Purchase Amount"].mean(),inplace=True)

C:\Users\Gnanajothi.M\AppData\Local\Temp\ipykernel_23640\120072482.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  calls["Satisfaction Rating"]=calls["Satisfaction Rating"].fillna(calls["Purchase Amount"].mean(),inplace=True)

In [128]:
calls.isnull().sum()

Call number            0
Customer ID            0
Duration               0
Representative         0
Date of Call           0
Purchase Amount        0
Satisfaction Rating    0
dtype: int64

In [129]:
calls["Representative"]=calls["Representative"].fillna("unknown",inplace=True)

C:\Users\Gnanajothi.M\AppData\Local\Temp\ipykernel_23640\1471799949.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  calls["Representative"]=calls["Representative"].fillna("unknown",inplace=True)

In [130]:
calls.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Call number          1000 non-null   str
 1   Customer ID          1000 non-null   str
 2   Duration             1000 non-null   int64
 3   Representative       1000 non-null   str
 4   Date of Call         1000 non-null   datetime64[us]
 5   Purchase Amount      1000 non-null   int64
 6   Satisfaction Rating  1000 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 54.8 KB

To check duplicates

In [133]:
calls.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [134]:
calls.duplicated().sum()

np.int64(0)

axis=1 row| axis=0 column

In [137]:
calls.drop_duplicates().all(axis=1).sum()

np.int64(999)

In [138]:
calls[calls.duplicated()]

Empty DataFrame
Columns: [Call number, Customer ID, Duration, Representative, Date of Call, Purchase Amount, Satisfaction Rating]
Index: []

In [140]:
calls.drop_duplicates(inplace=True)

In [142]:
calls["Date of Call"]=pd.to_datetime(calls["Date of Call"])

In [149]:
calls.dtypes

Call number                  str
Customer ID                  str
Duration                   int64
Representative               str
Date of Call      datetime64[us]
Purchase                   int64
Rating                   float64
dtype: object

In [145]:
calls.columns

Index(['Call number', 'Customer ID', 'Duration', 'Representative',
       'Date of Call', 'Purchase Amount', 'Satisfaction Rating'],
      dtype='str')

renaming

In [148]:
calls.rename(columns={"Purchase Amount":"Purchase","Satisfaction Rating":"Rating"},inplace=True)

In [150]:
calls.to_csv("cleaned_callcenter_data.csv",index=False)

data frame collection of rows and columns
one columns=series

In [155]:
calls[["Purchase","Rating","Representative"]]

     Purchase  Rating Representative
0         128  96.623            R05
1         135  96.623            R05
2          66  96.623            R02
3          22   2.900            R02
4          31   2.800            R01
..        ...     ...            ...
995        28   3.900            R05
996       215   3.800            R04
997       115   2.300            R05
998        64   3.700            R05
999        40   3.900            R01

[1000 rows x 3 columns]

In [157]:
calls.Rating[calls.Rating<3]

3      2.9
4      2.8
9      2.9
23     2.1
28     2.9
      ...
979    2.1
980    2.8
983    1.7
993    2.9
997    2.3
Name: Rating, Length: 144, dtype: float64

In [159]:
calls.Rating.sort_values(ascending=False)

1      96.623
0      96.623
2      96.623
39      5.000
921     5.000
        ...
128     1.000
557     0.900
180     0.700
445     0.700
69      0.000
Name: Rating, Length: 1000, dtype: float64